# Generated by Django 4.0.5 on 2023-05-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_location_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
